version: '3.8'

services:
  database:
    container_name: energy-db
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=energydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_tables.sql:/docker-entrypoint-initdb.d/01_init_tables.sql
      - ./sample_data.sql:/docker-entrypoint-initdb.d/02_sample_data.sql

  rabbitmq:
    container_name: energy-rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data: